#!/bin/bash

./compile.sh ex0.idr
./compile.sh ex1.idr
./compile.sh ex2.idr
./compile.sh ex3.idr
./compile.sh ex4.idr
./compile.sh ex5.idr
./compile.sh ex6.idr
./compile.sh ex7.idr
./compile.sh ex8.idr
./compile.sh ex9.idr
./compile.sh ex10.idr
./compile.sh ex11.idr
./compile.sh ex12.idr
./compile.sh ex13.idr
./compile.sh ex14.idr
./compile.sh ex15.idr
./compile.sh ex16.idr
./compile.sh ex17.idr
./compile.sh ex18.idr
./compile.sh ex19.idr
./compile.sh ex20.idr
./compile.sh ex21.idr
./compile.sh ex22.idr
./compile.sh ex23.idr
./compile.sh ex24.idr
./compile.sh ex25.idr
./compile.sh ex26.idr
./compile.sh ex27.idr
./compile.sh ex28.idr
